name: Python Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '.github/workflows/python.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - '.github/workflows/python.yml'

jobs:
  test:
    name: Test Python Utilities
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow pytest

    - name: Run Icon Validation
      run: |
        python validate_icons.py

    - name: Test Icon Generation
      run: |
        python generate_icon.py
        python validate_icons.py
